# -*- coding: utf-8 -*-
"""notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/174qUSVv0Mz9Lki-YN00tBSA8CrSZ0j7M

# Main Feedback Generation Notebook
This notebook handles preprocessing, model interaction, and feedback generation.

**--Set up: Github, Paths, Imports**
"""

# Commented out IPython magic to ensure Python compatibility.
# Mount Google Drive (optional, you'll get a prompt to authorize account)
# from google.colab import drive
# drive.mount('/content/drive')

# Start in root Colab directory to avoid nesting
# %cd /content

# Clone your GitHub repo (replace with your actual repo URL)
!git clone https://github.com/ML-name/project.git
# %cd project

# List all branches (optional, for checking)
# !git branch -a

# Checkout YOUR branch (!!replace "your-branch-name"!!)
!git checkout -b model/prompting origin/model/prompting

"""**--Install required libraries**"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -r requirements.txt --quiet

# Add src folder to python path to edit python files
import sys
sys.path.append('/content/project/')

from google.colab import userdata
import os
openai_key = userdata.get("OPENAI_API_KEY")
os.environ["OPENAI_API_KEY"] = openai_key

"""**--Import modules (youre working on)**
<br>*each of our classes will be what will merge to this notebook (im p sure)*
<br>only loads what you explicitly request
<br>(this helps keep memory low and import fast)
<br> *the following is an example with my Rubric module*
"""

!pip install --upgrade openai --quiet

from tropos import StudentSubmission
from tropos.models import gpt

example = StudentSubmission(
    "/content/project/data/raw/Student_1/Student_1_Part_1.docx",
    "/content/project/data/raw/Requirements.docx")
target = StudentSubmission(
    "/content/project/data/unmarked_raw/Uncommented_Student_1.docx",
    "/content/project/data/raw/Requirements.docx")

feedback = gpt.generate_feedback(example, target)
print(feedback)