# -*- coding: utf-8 -*-
"""01_data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ypqWAQ683iONXaOVVIHubYOFY2lR3aPM

**--Connect to drive, github, branch, src**
"""

# Commented out IPython magic to ensure Python compatibility.
# Mount Google Drive (optional, you'll get a prompt to authorize account)
# from google.colab import drive
# drive.mount('/content/drive')

# Start in root Colab directory to avoid nesting
# %cd /content

# Clone your GitHub repo (replace with your actual repo URL)
!git clone https://github.com/ML-name/project.git
# %cd project

# List all branches (optional, for checking)
!git branch -a

# Checkout YOUR branch (!!replace "your-branch-name"!!)
!git checkout -b your-branch-name origin/your-branch-name

# Add your src folder to the Python path
import sys
sys.path.append('/content/project/tropos/src')

# import data path for loading files
import os
data_path = os.path.join('/content/project/tropos/data', 'raw')

"""**--Install required libraries**"""

# docx library for Document
!pip install python-docx

"""**--Import class youre working on**
<br>*each of our classes will be what will merge to this notebook (im p sure)*
<br>only loads what you explicitly request
<br>(this helps keep memory low and import fast)

**-- *(example with mine)* Rubric Class**
"""

# REPLACE with YOURS :)
from preprocess_docx.rubric import parse_rubric, Rubric

# (replace with yours) to confirm everything is working
rubric = Rubric()
print("Rubric initialized:", rubric)

"""[[Remember to save your files
<br>and it's **highly recommended to clear output before pushing to GitHub**,
<br>this will help with merge conflicts and easy peer review.]]
<br>*(Edit >> Clear all outputs)*
"""